// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<FfiCommand> commandPause() =>
    RustLib.instance.api.crateApiCommandPause();

Future<FfiCommand> commandResume() =>
    RustLib.instance.api.crateApiCommandResume();

Future<FfiCommand> commandToggle() =>
    RustLib.instance.api.crateApiCommandToggle();

Future<FfiCommand> commandStop() => RustLib.instance.api.crateApiCommandStop();

Future<FfiCommand> commandNext() => RustLib.instance.api.crateApiCommandNext();

Future<FfiCommand> commandPrevious() =>
    RustLib.instance.api.crateApiCommandPrevious();

Future<FfiCommand> commandSearch({required String keyword}) =>
    RustLib.instance.api.crateApiCommandSearch(keyword: keyword);

Future<FfiCommand> commandSearchMore(
        {required String keyword, required int page}) =>
    RustLib.instance.api
        .crateApiCommandSearchMore(keyword: keyword, page: page);

Future<FfiCommand> commandPlay({required SongDto song}) =>
    RustLib.instance.api.crateApiCommandPlay(song: song);

Future<FfiCommand> commandQueueAdd({required SongDto song}) =>
    RustLib.instance.api.crateApiCommandQueueAdd(song: song);

Future<FfiCommand> commandQueueRemove({required int index}) =>
    RustLib.instance.api.crateApiCommandQueueRemove(index: index);

Future<FfiCommand> commandQueueClear() =>
    RustLib.instance.api.crateApiCommandQueueClear();

Future<VoicefoxController> newDesktop() =>
    RustLib.instance.api.crateApiNewDesktop();

Future<VoicefoxState> state({required VoicefoxController controller}) =>
    RustLib.instance.api.crateApiState(controller: controller);

Future<void> dispatch(
        {required VoicefoxController controller,
        required FfiCommand command}) =>
    RustLib.instance.api
        .crateApiDispatch(controller: controller, command: command);

Future<VoicefoxEventStream> subscribe(
        {required VoicefoxController controller}) =>
    RustLib.instance.api.crateApiSubscribe(controller: controller);

Future<VoicefoxEvent> eventNext({required VoicefoxEventStream stream}) =>
    RustLib.instance.api.crateApiEventNext(stream: stream);
