// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1800268501;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'voicefox_ffi',
    ioDirectory: '../ffi/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<FfiCommand> crateApiCommandNext();

  Future<FfiCommand> crateApiCommandPause();

  Future<FfiCommand> crateApiCommandPlay({required SongDto song});

  Future<FfiCommand> crateApiCommandPrevious();

  Future<FfiCommand> crateApiCommandQueueAdd({required SongDto song});

  Future<FfiCommand> crateApiCommandQueueClear();

  Future<FfiCommand> crateApiCommandQueueRemove({required int index});

  Future<FfiCommand> crateApiCommandResume();

  Future<FfiCommand> crateApiCommandSearch({required String keyword});

  Future<FfiCommand> crateApiCommandSearchMore(
      {required String keyword, required int page});

  Future<FfiCommand> crateApiCommandStop();

  Future<FfiCommand> crateApiCommandToggle();

  Future<void> crateApiDispatch(
      {required VoicefoxController controller, required FfiCommand command});

  Future<VoicefoxEvent> crateApiEventNext(
      {required VoicefoxEventStream stream});

  Future<VoicefoxController> crateApiNewDesktop();

  Future<VoicefoxState> crateApiState({required VoicefoxController controller});

  Future<VoicefoxEventStream> crateApiSubscribe(
      {required VoicefoxController controller});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_VoicefoxController;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_VoicefoxController;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VoicefoxControllerPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_VoicefoxEventStream;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_VoicefoxEventStream;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_VoicefoxEventStreamPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FfiCommand> crateApiCommandNext() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandNextConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandNextConstMeta => const TaskConstMeta(
        debugName: "command_next",
        argNames: [],
      );

  @override
  Future<FfiCommand> crateApiCommandPause() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandPauseConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandPauseConstMeta => const TaskConstMeta(
        debugName: "command_pause",
        argNames: [],
      );

  @override
  Future<FfiCommand> crateApiCommandPlay({required SongDto song}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_song_dto(song, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandPlayConstMeta,
      argValues: [song],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandPlayConstMeta => const TaskConstMeta(
        debugName: "command_play",
        argNames: ["song"],
      );

  @override
  Future<FfiCommand> crateApiCommandPrevious() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandPreviousConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandPreviousConstMeta => const TaskConstMeta(
        debugName: "command_previous",
        argNames: [],
      );

  @override
  Future<FfiCommand> crateApiCommandQueueAdd({required SongDto song}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_song_dto(song, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandQueueAddConstMeta,
      argValues: [song],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandQueueAddConstMeta => const TaskConstMeta(
        debugName: "command_queue_add",
        argNames: ["song"],
      );

  @override
  Future<FfiCommand> crateApiCommandQueueClear() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandQueueClearConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandQueueClearConstMeta => const TaskConstMeta(
        debugName: "command_queue_clear",
        argNames: [],
      );

  @override
  Future<FfiCommand> crateApiCommandQueueRemove({required int index}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(index, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandQueueRemoveConstMeta,
      argValues: [index],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandQueueRemoveConstMeta => const TaskConstMeta(
        debugName: "command_queue_remove",
        argNames: ["index"],
      );

  @override
  Future<FfiCommand> crateApiCommandResume() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandResumeConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandResumeConstMeta => const TaskConstMeta(
        debugName: "command_resume",
        argNames: [],
      );

  @override
  Future<FfiCommand> crateApiCommandSearch({required String keyword}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(keyword, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandSearchConstMeta,
      argValues: [keyword],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandSearchConstMeta => const TaskConstMeta(
        debugName: "command_search",
        argNames: ["keyword"],
      );

  @override
  Future<FfiCommand> crateApiCommandSearchMore(
      {required String keyword, required int page}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(keyword, serializer);
        sse_encode_u_32(page, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandSearchMoreConstMeta,
      argValues: [keyword, page],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandSearchMoreConstMeta => const TaskConstMeta(
        debugName: "command_search_more",
        argNames: ["keyword", "page"],
      );

  @override
  Future<FfiCommand> crateApiCommandStop() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandStopConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandStopConstMeta => const TaskConstMeta(
        debugName: "command_stop",
        argNames: [],
      );

  @override
  Future<FfiCommand> crateApiCommandToggle() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_command,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCommandToggleConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCommandToggleConstMeta => const TaskConstMeta(
        debugName: "command_toggle",
        argNames: [],
      );

  @override
  Future<void> crateApiDispatch(
      {required VoicefoxController controller, required FfiCommand command}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
            controller, serializer);
        sse_encode_box_autoadd_ffi_command(command, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDispatchConstMeta,
      argValues: [controller, command],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDispatchConstMeta => const TaskConstMeta(
        debugName: "dispatch",
        argNames: ["controller", "command"],
      );

  @override
  Future<VoicefoxEvent> crateApiEventNext(
      {required VoicefoxEventStream stream}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
            stream, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_voicefox_event,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEventNextConstMeta,
      argValues: [stream],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEventNextConstMeta => const TaskConstMeta(
        debugName: "event_next",
        argNames: ["stream"],
      );

  @override
  Future<VoicefoxController> crateApiNewDesktop() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNewDesktopConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNewDesktopConstMeta => const TaskConstMeta(
        debugName: "new_desktop",
        argNames: [],
      );

  @override
  Future<VoicefoxState> crateApiState(
      {required VoicefoxController controller}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
            controller, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_voicefox_state,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiStateConstMeta,
      argValues: [controller],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiStateConstMeta => const TaskConstMeta(
        debugName: "state",
        argNames: ["controller"],
      );

  @override
  Future<VoicefoxEventStream> crateApiSubscribe(
      {required VoicefoxController controller}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
            controller, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSubscribeConstMeta,
      argValues: [controller],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSubscribeConstMeta => const TaskConstMeta(
        debugName: "subscribe",
        argNames: ["controller"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_VoicefoxController => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_VoicefoxController => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_VoicefoxEventStream => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_VoicefoxEventStream => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream;

  @protected
  VoicefoxController
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VoicefoxControllerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VoicefoxEventStream
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VoicefoxEventStreamImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VoicefoxEventStream
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VoicefoxEventStreamImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VoicefoxController
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VoicefoxControllerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VoicefoxController
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VoicefoxControllerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VoicefoxEventStream
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VoicefoxEventStreamImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FfiCommand dco_decode_box_autoadd_ffi_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_command(raw);
  }

  @protected
  SongDto dco_decode_box_autoadd_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_song_dto(raw);
  }

  @protected
  FfiCommand dco_decode_ffi_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return FfiCommand_Pause();
      case 1:
        return FfiCommand_Resume();
      case 2:
        return FfiCommand_Toggle();
      case 3:
        return FfiCommand_Stop();
      case 4:
        return FfiCommand_SeekMs(
          dco_decode_u_64(raw[1]),
        );
      case 5:
        return FfiCommand_PlaySong(
          song: dco_decode_box_autoadd_song_dto(raw[1]),
        );
      case 6:
        return FfiCommand_QueueAdd(
          song: dco_decode_box_autoadd_song_dto(raw[1]),
          next: dco_decode_bool(raw[2]),
        );
      case 7:
        return FfiCommand_QueueRemove(
          index: dco_decode_u_32(raw[1]),
        );
      case 8:
        return FfiCommand_QueueClear();
      case 9:
        return FfiCommand_Next();
      case 10:
        return FfiCommand_Previous();
      case 11:
        return FfiCommand_Search(
          keyword: dco_decode_String(raw[1]),
        );
      case 12:
        return FfiCommand_SearchMore(
          keyword: dco_decode_String(raw[1]),
          page: dco_decode_u_32(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<LyricLineDto> dco_decode_list_lyric_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lyric_line_dto).toList();
  }

  @protected
  List<PlaylistDto> dco_decode_list_playlist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playlist_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SongDto> dco_decode_list_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_song_dto).toList();
  }

  @protected
  LyricLineDto dco_decode_lyric_line_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LyricLineDto(
      timestampMs: dco_decode_u_64(arr[0]),
      durationMs: dco_decode_u_64(arr[1]),
      text: dco_decode_String(arr[2]),
    );
  }

  @protected
  LyricsDto dco_decode_lyrics_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return LyricsDto(
      currentLine: dco_decode_u_32(arr[0]),
      positionMs: dco_decode_u_64(arr[1]),
      lines: dco_decode_list_lyric_line_dto(arr[2]),
      translation: dco_decode_opt_String(arr[3]),
      isEmpty: dco_decode_bool(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  SongDto? dco_decode_opt_box_autoadd_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_song_dto(raw);
  }

  @protected
  PlaybackDto dco_decode_playback_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PlaybackDto(
      state: dco_decode_String(arr[0]),
      song: dco_decode_opt_box_autoadd_song_dto(arr[1]),
      positionMs: dco_decode_u_64(arr[2]),
      durationMs: dco_decode_u_64(arr[3]),
      volume: dco_decode_u_32(arr[4]),
      generation: dco_decode_u_64(arr[5]),
    );
  }

  @protected
  PlaylistDto dco_decode_playlist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return PlaylistDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      source: dco_decode_String(arr[2]),
      coverUrl: dco_decode_opt_String(arr[3]),
      songCount: dco_decode_u_32(arr[4]),
      description: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  SearchDto dco_decode_search_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SearchDto(
      keyword: dco_decode_String(arr[0]),
      page: dco_decode_u_32(arr[1]),
      hasMore: dco_decode_bool(arr[2]),
      items: dco_decode_list_song_dto(arr[3]),
      requestId: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  SongDto dco_decode_song_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SongDto(
      id: dco_decode_String(arr[0]),
      source: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      singer: dco_decode_String(arr[3]),
      albumName: dco_decode_String(arr[4]),
      durationMs: dco_decode_u_64(arr[5]),
      coverUrl: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VoicefoxEvent dco_decode_voicefox_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return VoicefoxEvent(
      kind: dco_decode_String(arr[0]),
      requestId: dco_decode_u_64(arr[1]),
      keyword: dco_decode_opt_String(arr[2]),
      page: dco_decode_u_32(arr[3]),
      append: dco_decode_bool(arr[4]),
      hasMore: dco_decode_bool(arr[5]),
      message: dco_decode_opt_String(arr[6]),
      song: dco_decode_opt_box_autoadd_song_dto(arr[7]),
      items: dco_decode_list_song_dto(arr[8]),
      queue: dco_decode_list_song_dto(arr[9]),
      queueIndex: dco_decode_u_32(arr[10]),
    );
  }

  @protected
  VoicefoxState dco_decode_voicefox_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return VoicefoxState(
      playback: dco_decode_playback_dto(arr[0]),
      queue: dco_decode_list_song_dto(arr[1]),
      queueIndex: dco_decode_u_32(arr[2]),
      search: dco_decode_search_dto(arr[3]),
      lyrics: dco_decode_lyrics_dto(arr[4]),
      playlists: dco_decode_list_playlist_dto(arr[5]),
    );
  }

  @protected
  VoicefoxController
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VoicefoxControllerImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  VoicefoxEventStream
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VoicefoxEventStreamImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  VoicefoxEventStream
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VoicefoxEventStreamImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  VoicefoxController
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VoicefoxControllerImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  VoicefoxController
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VoicefoxControllerImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  VoicefoxEventStream
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VoicefoxEventStreamImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FfiCommand sse_decode_box_autoadd_ffi_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_command(deserializer));
  }

  @protected
  SongDto sse_decode_box_autoadd_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_song_dto(deserializer));
  }

  @protected
  FfiCommand sse_decode_ffi_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return FfiCommand_Pause();
      case 1:
        return FfiCommand_Resume();
      case 2:
        return FfiCommand_Toggle();
      case 3:
        return FfiCommand_Stop();
      case 4:
        var var_field0 = sse_decode_u_64(deserializer);
        return FfiCommand_SeekMs(var_field0);
      case 5:
        var var_song = sse_decode_box_autoadd_song_dto(deserializer);
        return FfiCommand_PlaySong(song: var_song);
      case 6:
        var var_song = sse_decode_box_autoadd_song_dto(deserializer);
        var var_next = sse_decode_bool(deserializer);
        return FfiCommand_QueueAdd(song: var_song, next: var_next);
      case 7:
        var var_index = sse_decode_u_32(deserializer);
        return FfiCommand_QueueRemove(index: var_index);
      case 8:
        return FfiCommand_QueueClear();
      case 9:
        return FfiCommand_Next();
      case 10:
        return FfiCommand_Previous();
      case 11:
        var var_keyword = sse_decode_String(deserializer);
        return FfiCommand_Search(keyword: var_keyword);
      case 12:
        var var_keyword = sse_decode_String(deserializer);
        var var_page = sse_decode_u_32(deserializer);
        return FfiCommand_SearchMore(keyword: var_keyword, page: var_page);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<LyricLineDto> sse_decode_list_lyric_line_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LyricLineDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lyric_line_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlaylistDto> sse_decode_list_playlist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlaylistDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SongDto> sse_decode_list_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SongDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_song_dto(deserializer));
    }
    return ans_;
  }

  @protected
  LyricLineDto sse_decode_lyric_line_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_text = sse_decode_String(deserializer);
    return LyricLineDto(
        timestampMs: var_timestampMs,
        durationMs: var_durationMs,
        text: var_text);
  }

  @protected
  LyricsDto sse_decode_lyrics_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_currentLine = sse_decode_u_32(deserializer);
    var var_positionMs = sse_decode_u_64(deserializer);
    var var_lines = sse_decode_list_lyric_line_dto(deserializer);
    var var_translation = sse_decode_opt_String(deserializer);
    var var_isEmpty = sse_decode_bool(deserializer);
    return LyricsDto(
        currentLine: var_currentLine,
        positionMs: var_positionMs,
        lines: var_lines,
        translation: var_translation,
        isEmpty: var_isEmpty);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SongDto? sse_decode_opt_box_autoadd_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_song_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaybackDto sse_decode_playback_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_state = sse_decode_String(deserializer);
    var var_song = sse_decode_opt_box_autoadd_song_dto(deserializer);
    var var_positionMs = sse_decode_u_64(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_volume = sse_decode_u_32(deserializer);
    var var_generation = sse_decode_u_64(deserializer);
    return PlaybackDto(
        state: var_state,
        song: var_song,
        positionMs: var_positionMs,
        durationMs: var_durationMs,
        volume: var_volume,
        generation: var_generation);
  }

  @protected
  PlaylistDto sse_decode_playlist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    var var_songCount = sse_decode_u_32(deserializer);
    var var_description = sse_decode_opt_String(deserializer);
    return PlaylistDto(
        id: var_id,
        name: var_name,
        source: var_source,
        coverUrl: var_coverUrl,
        songCount: var_songCount,
        description: var_description);
  }

  @protected
  SearchDto sse_decode_search_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_keyword = sse_decode_String(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_hasMore = sse_decode_bool(deserializer);
    var var_items = sse_decode_list_song_dto(deserializer);
    var var_requestId = sse_decode_u_64(deserializer);
    return SearchDto(
        keyword: var_keyword,
        page: var_page,
        hasMore: var_hasMore,
        items: var_items,
        requestId: var_requestId);
  }

  @protected
  SongDto sse_decode_song_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_singer = sse_decode_String(deserializer);
    var var_albumName = sse_decode_String(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    return SongDto(
        id: var_id,
        source: var_source,
        name: var_name,
        singer: var_singer,
        albumName: var_albumName,
        durationMs: var_durationMs,
        coverUrl: var_coverUrl);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VoicefoxEvent sse_decode_voicefox_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_requestId = sse_decode_u_64(deserializer);
    var var_keyword = sse_decode_opt_String(deserializer);
    var var_page = sse_decode_u_32(deserializer);
    var var_append = sse_decode_bool(deserializer);
    var var_hasMore = sse_decode_bool(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    var var_song = sse_decode_opt_box_autoadd_song_dto(deserializer);
    var var_items = sse_decode_list_song_dto(deserializer);
    var var_queue = sse_decode_list_song_dto(deserializer);
    var var_queueIndex = sse_decode_u_32(deserializer);
    return VoicefoxEvent(
        kind: var_kind,
        requestId: var_requestId,
        keyword: var_keyword,
        page: var_page,
        append: var_append,
        hasMore: var_hasMore,
        message: var_message,
        song: var_song,
        items: var_items,
        queue: var_queue,
        queueIndex: var_queueIndex);
  }

  @protected
  VoicefoxState sse_decode_voicefox_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_playback = sse_decode_playback_dto(deserializer);
    var var_queue = sse_decode_list_song_dto(deserializer);
    var var_queueIndex = sse_decode_u_32(deserializer);
    var var_search = sse_decode_search_dto(deserializer);
    var var_lyrics = sse_decode_lyrics_dto(deserializer);
    var var_playlists = sse_decode_list_playlist_dto(deserializer);
    return VoicefoxState(
        playback: var_playback,
        queue: var_queue,
        queueIndex: var_queueIndex,
        search: var_search,
        lyrics: var_lyrics,
        playlists: var_playlists);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          VoicefoxController self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VoicefoxControllerImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          VoicefoxEventStream self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VoicefoxEventStreamImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          VoicefoxEventStream self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VoicefoxEventStreamImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          VoicefoxController self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VoicefoxControllerImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxController(
          VoicefoxController self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VoicefoxControllerImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVoicefoxEventStream(
          VoicefoxEventStream self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VoicefoxEventStreamImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ffi_command(
      FfiCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_command(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_song_dto(SongDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_song_dto(self, serializer);
  }

  @protected
  void sse_encode_ffi_command(FfiCommand self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case FfiCommand_Pause():
        sse_encode_i_32(0, serializer);
      case FfiCommand_Resume():
        sse_encode_i_32(1, serializer);
      case FfiCommand_Toggle():
        sse_encode_i_32(2, serializer);
      case FfiCommand_Stop():
        sse_encode_i_32(3, serializer);
      case FfiCommand_SeekMs(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_u_64(field0, serializer);
      case FfiCommand_PlaySong(song: final song):
        sse_encode_i_32(5, serializer);
        sse_encode_box_autoadd_song_dto(song, serializer);
      case FfiCommand_QueueAdd(song: final song, next: final next):
        sse_encode_i_32(6, serializer);
        sse_encode_box_autoadd_song_dto(song, serializer);
        sse_encode_bool(next, serializer);
      case FfiCommand_QueueRemove(index: final index):
        sse_encode_i_32(7, serializer);
        sse_encode_u_32(index, serializer);
      case FfiCommand_QueueClear():
        sse_encode_i_32(8, serializer);
      case FfiCommand_Next():
        sse_encode_i_32(9, serializer);
      case FfiCommand_Previous():
        sse_encode_i_32(10, serializer);
      case FfiCommand_Search(keyword: final keyword):
        sse_encode_i_32(11, serializer);
        sse_encode_String(keyword, serializer);
      case FfiCommand_SearchMore(keyword: final keyword, page: final page):
        sse_encode_i_32(12, serializer);
        sse_encode_String(keyword, serializer);
        sse_encode_u_32(page, serializer);
    }
  }

  @protected
  void sse_encode_list_lyric_line_dto(
      List<LyricLineDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lyric_line_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist_dto(
      List<PlaylistDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_song_dto(List<SongDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_song_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_lyric_line_dto(LyricLineDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_lyrics_dto(LyricsDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.currentLine, serializer);
    sse_encode_u_64(self.positionMs, serializer);
    sse_encode_list_lyric_line_dto(self.lines, serializer);
    sse_encode_opt_String(self.translation, serializer);
    sse_encode_bool(self.isEmpty, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_song_dto(
      SongDto? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_song_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_playback_dto(PlaybackDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.state, serializer);
    sse_encode_opt_box_autoadd_song_dto(self.song, serializer);
    sse_encode_u_64(self.positionMs, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_u_32(self.volume, serializer);
    sse_encode_u_64(self.generation, serializer);
  }

  @protected
  void sse_encode_playlist_dto(PlaylistDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_u_32(self.songCount, serializer);
    sse_encode_opt_String(self.description, serializer);
  }

  @protected
  void sse_encode_search_dto(SearchDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.keyword, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_bool(self.hasMore, serializer);
    sse_encode_list_song_dto(self.items, serializer);
    sse_encode_u_64(self.requestId, serializer);
  }

  @protected
  void sse_encode_song_dto(SongDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.source, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.singer, serializer);
    sse_encode_String(self.albumName, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_voicefox_event(VoicefoxEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_u_64(self.requestId, serializer);
    sse_encode_opt_String(self.keyword, serializer);
    sse_encode_u_32(self.page, serializer);
    sse_encode_bool(self.append, serializer);
    sse_encode_bool(self.hasMore, serializer);
    sse_encode_opt_String(self.message, serializer);
    sse_encode_opt_box_autoadd_song_dto(self.song, serializer);
    sse_encode_list_song_dto(self.items, serializer);
    sse_encode_list_song_dto(self.queue, serializer);
    sse_encode_u_32(self.queueIndex, serializer);
  }

  @protected
  void sse_encode_voicefox_state(VoicefoxState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_playback_dto(self.playback, serializer);
    sse_encode_list_song_dto(self.queue, serializer);
    sse_encode_u_32(self.queueIndex, serializer);
    sse_encode_search_dto(self.search, serializer);
    sse_encode_lyrics_dto(self.lyrics, serializer);
    sse_encode_list_playlist_dto(self.playlists, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class VoicefoxControllerImpl extends RustOpaque implements VoicefoxController {
  // Not to be used by end users
  VoicefoxControllerImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VoicefoxControllerImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VoicefoxController,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VoicefoxController,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_VoicefoxControllerPtr,
  );
}

@sealed
class VoicefoxEventStreamImpl extends RustOpaque
    implements VoicefoxEventStream {
  // Not to be used by end users
  VoicefoxEventStreamImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VoicefoxEventStreamImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_VoicefoxEventStream,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_VoicefoxEventStream,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_VoicefoxEventStreamPtr,
  );
}
