// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VoicefoxController>>
abstract class VoicefoxController implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VoicefoxEventStream>>
abstract class VoicefoxEventStream implements RustOpaqueInterface {}

@freezed
sealed class FfiCommand with _$FfiCommand {
  const FfiCommand._();

  const factory FfiCommand.pause() = FfiCommand_Pause;
  const factory FfiCommand.resume() = FfiCommand_Resume;
  const factory FfiCommand.toggle() = FfiCommand_Toggle;
  const factory FfiCommand.stop() = FfiCommand_Stop;
  const factory FfiCommand.seekMs(
    BigInt field0,
  ) = FfiCommand_SeekMs;
  const factory FfiCommand.playSong({
    required SongDto song,
  }) = FfiCommand_PlaySong;
  const factory FfiCommand.queueAdd({
    required SongDto song,
    required bool next,
  }) = FfiCommand_QueueAdd;
  const factory FfiCommand.queueRemove({
    required int index,
  }) = FfiCommand_QueueRemove;
  const factory FfiCommand.queueClear() = FfiCommand_QueueClear;
  const factory FfiCommand.next() = FfiCommand_Next;
  const factory FfiCommand.previous() = FfiCommand_Previous;
  const factory FfiCommand.search({
    required String keyword,
  }) = FfiCommand_Search;
  const factory FfiCommand.searchMore({
    required String keyword,
    required int page,
  }) = FfiCommand_SearchMore;
}

class LyricLineDto {
  final BigInt timestampMs;
  final BigInt durationMs;
  final String text;

  const LyricLineDto({
    required this.timestampMs,
    required this.durationMs,
    required this.text,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^ durationMs.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricLineDto &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          durationMs == other.durationMs &&
          text == other.text;
}

class LyricsDto {
  final int currentLine;
  final BigInt positionMs;
  final List<LyricLineDto> lines;
  final String? translation;
  final bool isEmpty;

  const LyricsDto({
    required this.currentLine,
    required this.positionMs,
    required this.lines,
    this.translation,
    required this.isEmpty,
  });

  @override
  int get hashCode =>
      currentLine.hashCode ^
      positionMs.hashCode ^
      lines.hashCode ^
      translation.hashCode ^
      isEmpty.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsDto &&
          runtimeType == other.runtimeType &&
          currentLine == other.currentLine &&
          positionMs == other.positionMs &&
          lines == other.lines &&
          translation == other.translation &&
          isEmpty == other.isEmpty;
}

class PlaybackDto {
  final String state;
  final SongDto? song;
  final BigInt positionMs;
  final BigInt durationMs;
  final int volume;
  final BigInt generation;

  const PlaybackDto({
    required this.state,
    this.song,
    required this.positionMs,
    required this.durationMs,
    required this.volume,
    required this.generation,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      song.hashCode ^
      positionMs.hashCode ^
      durationMs.hashCode ^
      volume.hashCode ^
      generation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackDto &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          song == other.song &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          volume == other.volume &&
          generation == other.generation;
}

class PlaylistDto {
  final String id;
  final String name;
  final String source;
  final String? coverUrl;
  final int songCount;
  final String? description;

  const PlaylistDto({
    required this.id,
    required this.name,
    required this.source,
    this.coverUrl,
    required this.songCount,
    this.description,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      source.hashCode ^
      coverUrl.hashCode ^
      songCount.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          source == other.source &&
          coverUrl == other.coverUrl &&
          songCount == other.songCount &&
          description == other.description;
}

class SearchDto {
  final String keyword;
  final int page;
  final bool hasMore;
  final List<SongDto> items;
  final BigInt requestId;

  const SearchDto({
    required this.keyword,
    required this.page,
    required this.hasMore,
    required this.items,
    required this.requestId,
  });

  @override
  int get hashCode =>
      keyword.hashCode ^
      page.hashCode ^
      hasMore.hashCode ^
      items.hashCode ^
      requestId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchDto &&
          runtimeType == other.runtimeType &&
          keyword == other.keyword &&
          page == other.page &&
          hasMore == other.hasMore &&
          items == other.items &&
          requestId == other.requestId;
}

class SongDto {
  final String id;
  final String source;
  final String name;
  final String singer;
  final String albumName;
  final BigInt durationMs;
  final String? coverUrl;

  const SongDto({
    required this.id,
    required this.source,
    required this.name,
    required this.singer,
    required this.albumName,
    required this.durationMs,
    this.coverUrl,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      source.hashCode ^
      name.hashCode ^
      singer.hashCode ^
      albumName.hashCode ^
      durationMs.hashCode ^
      coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SongDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          source == other.source &&
          name == other.name &&
          singer == other.singer &&
          albumName == other.albumName &&
          durationMs == other.durationMs &&
          coverUrl == other.coverUrl;
}

class VoicefoxEvent {
  final String kind;
  final BigInt requestId;
  final String? keyword;
  final int page;
  final bool append;
  final bool hasMore;
  final String? message;
  final SongDto? song;
  final List<SongDto> items;
  final List<SongDto> queue;
  final int queueIndex;

  const VoicefoxEvent({
    required this.kind,
    required this.requestId,
    this.keyword,
    required this.page,
    required this.append,
    required this.hasMore,
    this.message,
    this.song,
    required this.items,
    required this.queue,
    required this.queueIndex,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      requestId.hashCode ^
      keyword.hashCode ^
      page.hashCode ^
      append.hashCode ^
      hasMore.hashCode ^
      message.hashCode ^
      song.hashCode ^
      items.hashCode ^
      queue.hashCode ^
      queueIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoicefoxEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          requestId == other.requestId &&
          keyword == other.keyword &&
          page == other.page &&
          append == other.append &&
          hasMore == other.hasMore &&
          message == other.message &&
          song == other.song &&
          items == other.items &&
          queue == other.queue &&
          queueIndex == other.queueIndex;
}

class VoicefoxState {
  final PlaybackDto playback;
  final List<SongDto> queue;
  final int queueIndex;
  final SearchDto search;
  final LyricsDto lyrics;
  final List<PlaylistDto> playlists;

  const VoicefoxState({
    required this.playback,
    required this.queue,
    required this.queueIndex,
    required this.search,
    required this.lyrics,
    required this.playlists,
  });

  @override
  int get hashCode =>
      playback.hashCode ^
      queue.hashCode ^
      queueIndex.hashCode ^
      search.hashCode ^
      lyrics.hashCode ^
      playlists.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VoicefoxState &&
          runtimeType == other.runtimeType &&
          playback == other.playback &&
          queue == other.queue &&
          queueIndex == other.queueIndex &&
          search == other.search &&
          lyrics == other.lyrics &&
          playlists == other.playlists;
}
