[package]
name = "lx-player"
version.workspace = true
edition.workspace = true

[features]
default = ["desktop-mpv"]
desktop-mpv = ["dep:libmpv2"]
build_libmpv = ["desktop-mpv", "libmpv2/build_libmpv"]

[dependencies]
lx-core = { path = "../core" }

tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
libmpv2 = { workspace = true, optional = true }
